### ISSUE TITLE
Add TypeScript Support (Rewrite in TypeScript)

### ISSUE THREAD

**Issue by arya2004** [arya2004/AutoExpress.js#3]
We would like to enhance the project by rewriting it in TypeScript to take advantage of type safety and better development tooling. This includes converting existing JavaScript files to TypeScript and ensuring the project builds correctly with TypeScript configurations.

**Tasks:**
- Set up TypeScript in the project.
- Convert JavaScript files to TypeScript, including adding type definitions.
- Ensure compatibility with existing features like database connections and MVC/API structure.
- Add any necessary type declarations for dependencies.
- Update documentation to reflect changes.
- Ensure all tests pass after conversion.

**Expected Outcome:**
A fully working TypeScript version of the project with the same functionality as the current JavaScript version.

**Comment by Rahulagg13** [comment]
Hey, can you assign this issue to me?

**Comment by arya2004** [comment]
@Rahulagg13 assigned!
