### ISSUE TITLE
Implement a `--flat` Option Similar to Angular CLI

### ISSUE THREAD

**Issue by arya2004** [arya2004/AutoExpress.js#5]
We would like to add a `--flat` option to the generator, similar to Angular CLI’s `--flat` argument. This would allow users to generate files without creating a new directory for the feature (e.g., models, controllers), directly within the root directory.

**Tasks:**
- Add the `--flat` argument to the CLI options.
- Implement logic to handle file generation in the root directory without creating subdirectories.
- Ensure that this option works across all available generator commands.
- Update tests to cover this new option.
- Document the usage of the `--flat` option.

**Expected Outcome:**
Users will have the option to generate files directly in the root directory without additional folders when using the `--flat` argument.

**Comment by Aaditya8C** [comment]
Hey can you assign this task to me?

**Comment by arya2004** [comment]
Sure @Aaditya8C 

All the best

**Comment by Aaditya8C** [comment]
Hey @arya2004 I've done the changes. Check it once and let me know if anything is missing.

**Comment by arya2004** [comment]
lgtm!
